import type { AnalysisCheckboxes } from '../../types/analysis.types'
import './AnalysisFieldsGrid.css'

interface AnalysisFieldsGridProps {
    checkboxes: AnalysisCheckboxes
    values: {
        flexibilityAnalysis: string
        biobitAnalysis: string
        muscularAsymmetry: string
        activeMotorControl: string
        muscleFatigue: string
        inertiaForceControl: string
    }
    onChange: (field: string, value: string) => void
    usedAI: boolean
    onRegenerate: () => void
    disabled?: boolean
}

function AnalysisFieldsGrid({
    checkboxes,
    values,
    onChange,
    usedAI,
    onRegenerate,
    disabled = false
}: AnalysisFieldsGridProps) {
    const fields = [
        { key: 'flexibilityAnalysis', checkbox: 'flexibility', label: '1. Flexibility Analysis' },
        { key: 'biobitAnalysis', checkbox: 'biobit', label: '2. Biobit Analysis' },
        { key: 'muscularAsymmetry', checkbox: 'asymmetry', label: '3. Muscular Asymmetry in Activation' },
        { key: 'activeMotorControl', checkbox: 'motorControl', label: '4. Active Motor Control Analysis' },
        { key: 'muscleFatigue', checkbox: 'fatigue', label: '5. Functional Muscle Fatigue Analysis' },
        { key: 'inertiaForceControl', checkbox: 'inertiaForce', label: '6. Inertia Force Control Analysis' }
    ]

    return (
        <div className="analysis-fields-grid">
            {fields.map(({ key, checkbox, label }) => {
                if (!checkboxes[checkbox as keyof AnalysisCheckboxes]) return null

                return (
                    <div key={key} className="form-group">
                        <label htmlFor={key}>
                            {label}
                            {usedAI && <span className="ai-badge">Generated by AI</span>}
                        </label>
                        <textarea
                            id={key}
                            name={key}
                            value={values[key as keyof typeof values]}
                            onChange={(e) => onChange(key, e.target.value)}
                            rows={5}
                            disabled={disabled}
                        />
                    </div>
                )
            })}

            <button
                type="button"
                className="btn-regenerate"
                onClick={onRegenerate}
                disabled={disabled}
            >
                {usedAI ? 'Regenerate with AI' : 'Generate with AI'}
            </button>
        </div>
    )
}

export default AnalysisFieldsGrid
